name: Build and push a CRF-only docker image

on:
  push:
    branches:
      - master
      - update-from-upstream
  pull_request:
    branches:
      - master

concurrency:
  group: gradle
  cancel-in-progress: true

permissions:
  contents: read
  checks: write
  statuses: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-tags: true
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: temurin
      - uses: gradle/actions/setup-gradle@v6
      - name: Build with Gradle
        run: ./gradlew clean assemble --info --stacktrace --no-daemon
      - name: Test with Gradle Jacoco
        run: ./gradlew test jacocoTestReport --no-daemon
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: ${{ !cancelled() }}
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'

  docker-build-crf:
    needs:
      - build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Login to registry
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v4
        with:
          registry: docker.evidenceprime.com
          username: ${{ secrets.DOCKER_PUBLIC_LOGIN }}
          password: ${{ secrets.DOCKER_PUBLIC_PASSWORD }}
      - name: Build and push image to registry
        id: docker_build
        uses: docker/build-push-action@v7
        env:
          DOCKER_BUILD_SUMMARY: false
        with:
          context: '.'
          file: Dockerfile.crf
          tags: docker.evidenceprime.com/grobid:${{ github.sha }}
          push: ${{ github.event_name == 'push' }}
          cache-from: type=gha,scope=crf
          cache-to: type=gha,scope=crf,mode=max
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
